language: php

php:
  - 5.6
  - 7.0
  
  
before_script: 
  - composer install --dev --no-interaction --prefer-source
  - cp ./.env.travis ./.env
  - touch ./database/testing.sqlite
  - php artisan migrate --database=sqlite_testing --no-interaction
  
script: vendor/bin/phpunit