language: php

php:
  - 5.6
  - 7.0
  
  
before_script: 
  - composer install --dev --no-interaction --prefer-source
  - touch ./database/sqlite_testing.sqlite
  - php artisan migrate --database = sqlite_testing
  
script: vendor/bin/phpunit